/** 
 * Class :- ACR_ConstantDeclarations
 * @author :- Perficient.
 * purpose:- Constant declarations for credit/refund implementation
 */
public with sharing class ACR_ConstantDeclarations {
	public static final String HR_ERROR_FUNCTIONALITY_NAME = 'HR Integration Batch Apex';
	public static final String APPROVAL_MATRIX_TRIGGER_ERROR = 'ACR_ApprovalMatrixTriggerHelper';
    public static final String OPERATION_NAME_TRIGGER= 'Update';
    public static final String OPERATION_NAME_BATCH_UPSERT= 'Upsert';
  
}