@isTest
public with sharing class Test_DocuSignAccountManagementAPI {

    static testMethod void testAPI() {
        new DocuSignAccountManagementAPI();
	    new DocuSignAccountManagementAPI.ArrayOfMember();
	    //new DocuSignAccountManagementAPI.GetAccountDistributorCodeResult_element();
	    //new DocuSignAccountManagementAPI.UpdateAccountSettingsResult_element();
	    new DocuSignAccountManagementAPI.CheckAccountMemberResult_element();
	    //new DocuSignAccountManagementAPI.UpdateMemberSettings_element();
	    //new DocuSignAccountManagementAPI.ArrayOfSeatDiscount();
	    //new DocuSignAccountManagementAPI.ArrayOfPlanGroupPlan();
	    new DocuSignAccountManagementAPI.GetMembershipSummaryResult_element();
	    //new DocuSignAccountManagementAPI.GetAccountSettings_element();
	    //new DocuSignAccountManagementAPI.GetProvisioningInformationResponse_element();
	    //new DocuSignAccountManagementAPI.GetProvisioningInformationResult_element();
	    //new DocuSignAccountManagementAPI.NewAccountResponse_element();
	    //new DocuSignAccountManagementAPI.GetPlanTypeResponse_element();
	    //new DocuSignAccountManagementAPI.ChangePasswordArg();
	    //new DocuSignAccountManagementAPI.SetConnectCredentialsResult_element();
	    new DocuSignAccountManagementAPI.ArrayOfMemberResult();
	    //new DocuSignAccountManagementAPI.GetMemberSettingsResult_element();
	    //new DocuSignAccountManagementAPI.SeatDiscount();
	    //new DocuSignAccountManagementAPI.GetAccountDistributorCode_element();
	    //new DocuSignAccountManagementAPI.GetSuccessorPlanInformationResult_element();
	    //new DocuSignAccountManagementAPI.GetPlanType_element();
	    //new DocuSignAccountManagementAPI.UpdateAccountSettingsResponse_element();
	    //new DocuSignAccountManagementAPI.GetConnectCredentialsResponse_element();
	    //new DocuSignAccountManagementAPI.GetAccountInformationResponse_element();
	    //new DocuSignAccountManagementAPI.GetMemberSettingsResponse_element();
	    //new DocuSignAccountManagementAPI.AuthenticateMemberExResult_element();
	    //new DocuSignAccountManagementAPI.ChangePassword_element();
	    //new DocuSignAccountManagementAPI.GetEncryptedPassword_element();
	    //new DocuSignAccountManagementAPI.AuthenticateMemberExResponse_element();
	    new DocuSignAccountManagementAPI.GetMembershipSummaryResponse_element();
	    //new DocuSignAccountManagementAPI.GetPlanGroupInformationResponse_element();
	    new DocuSignAccountManagementAPI.AddMembersToAccountResponse_element();
	    new DocuSignAccountManagementAPI.ArrayOfMembershipSummary();
	    //new DocuSignAccountManagementAPI.ChangePasswordResult_element();
	    //new DocuSignAccountManagementAPI.UpgradeRecipientAccountResult_element();
	    //new DocuSignAccountManagementAPI.GetAccountSettingsResult_element();
	    //new DocuSignAccountManagementAPI.GetSuccessorPlanInformationResponse_element();
	    //new DocuSignAccountManagementAPI.PlanGroupPlan();
	    new DocuSignAccountManagementAPI.AddMembersToAccount_element();
	    //new DocuSignAccountManagementAPI.GetProvisioningInformation_element();
	    new DocuSignAccountManagementAPI.MemberResult();
	    //new DocuSignAccountManagementAPI.AccountSettings();
	    //new DocuSignAccountManagementAPI.GetEncryptedPasswordResponse_element();
	    //new DocuSignAccountManagementAPI.GetConnectCredentials_element();
	    //new DocuSignAccountManagementAPI.Plan();
	    //new DocuSignAccountManagementAPI.AuthenticateMember_element();
	    //new DocuSignAccountManagementAPI.UpdateAccountSettings_element();
	    new DocuSignAccountManagementAPI.RequestError();
	    new DocuSignAccountManagementAPI.Member();
	    //new DocuSignAccountManagementAPI.GetAccountDistributorCodeResponse_element();
	    new DocuSignAccountManagementAPI.CheckAccountMember_element();
	    new DocuSignAccountManagementAPI.MemberSettings();
	    //new DocuSignAccountManagementAPI.ReferralInformation();
	    //new DocuSignAccountManagementAPI.ActivateSalesforceInstance_element();
	    //new DocuSignAccountManagementAPI.UpdateMemberSettingsResult_element();
	    //new DocuSignAccountManagementAPI.ChangeAccountPricePlanResponse_element();
	    new DocuSignAccountManagementAPI.CheckAccountMemberResponse_element();
	    //new DocuSignAccountManagementAPI.Ping_element();
	    //new DocuSignAccountManagementAPI.ChangeAccountPricePlanResult_element();
	    //new DocuSignAccountManagementAPI.AuthenticateMemberEx_element();
	    //new DocuSignAccountManagementAPI.GetMemberSettings_element();
	    new DocuSignAccountManagementAPI.GetMembershipSummary_element();
	    //new DocuSignAccountManagementAPI.ChangeAccountPricePlan_element();
	    //new DocuSignAccountManagementAPI.AuthenticateMemberResult_element();
	    //new DocuSignAccountManagementAPI.UpdateMemberSettingsResponse_element();
	    //new DocuSignAccountManagementAPI.NewAccountResult_element();
	    //new DocuSignAccountManagementAPI.CreditCardInformation();
	    //new DocuSignAccountManagementAPI.UpgradeRecipientAccount_element();
	    //new DocuSignAccountManagementAPI.GetPlanGroupInformation_element();
	    //new DocuSignAccountManagementAPI.ActivateSalesforceInstanceResult_element();
	    //new DocuSignAccountManagementAPI.GetPlanPricingInformationResult_element();
	    //new DocuSignAccountManagementAPI.UpgradeRecipientAccountResponse_element();
	    //new DocuSignAccountManagementAPI.GetPlanPricingInformation_element();
	    //new DocuSignAccountManagementAPI.GetPlanPricingInformationResponse_element();
	    new DocuSignAccountManagementAPI.MembershipSummary();
	    //new DocuSignAccountManagementAPI.SetConnectCredentialsResponse_element();
	    //new DocuSignAccountManagementAPI.GetAccountInformation_element();
	    //new DocuSignAccountManagementAPI.ActivateSalesforceInstanceResponse_element();
	    //new DocuSignAccountManagementAPI.GetEncryptedPasswordResult_element();
	    //new DocuSignAccountManagementAPI.GetAccountInformationResult_element();
	    //new DocuSignAccountManagementAPI.GetSuccessorPlanInformation_element();
	    new DocuSignAccountManagementAPI.AddMembersToAccountResult_element();
	    //new DocuSignAccountManagementAPI.PingResponse_element();
	    //new DocuSignAccountManagementAPI.GetConnectCredentialsResult_element();
	    //new DocuSignAccountManagementAPI.ArrayOfPlanGroup();
	    //new DocuSignAccountManagementAPI.AddressInformation();
	    //new DocuSignAccountManagementAPI.PlanGroup();
	    //new DocuSignAccountManagementAPI.ChangePasswordResponse_element();
	    //new DocuSignAccountManagementAPI.GetPlanGroupInformationResult_element();
	    //new DocuSignAccountManagementAPI.SetConnectCredentials_element();
	    //new DocuSignAccountManagementAPI.GetPlanTypeResult_element();
	    //new DocuSignAccountManagementAPI.GetAccountSettingsResponse_element();
	    //new DocuSignAccountManagementAPI.AuthenticateMemberResponse_element();
	    //new DocuSignAccountManagementAPI.ArrayOfPlan();
	    //new DocuSignAccountManagementAPI.NewAccount_element();
	    DocuSignAccountManagementAPI.AccountManagementServiceSoap client = new DocuSignAccountManagementAPI.AccountManagementServiceSoap();
	    
	    //try {client.GetProvisioningInformation(null);}catch(Exception e){}
	    try {client.CheckAccountMember(null,null);}catch(Exception e){}
        //try {client.ActivateSalesforceInstance(null,null,null,null,null,null);}catch(Exception e){}
        //try {client.UpgradeRecipientAccount(null,null,null,null,null,null,null,null,null,null);}catch(Exception e){}
        //try {client.UpdateAccountSettings(null,null);}catch(Exception e){}
        //try {client.GetPlanGroupInformation(null,null);}catch(Exception e){}
        //try {client.ChangePassword(null);}catch(Exception e){}
        //try {client.SetConnectCredentials(null,null,null,null,null);}catch(Exception e){}
        //try {client.GetAccountSettings(null);}catch(Exception e){}
        try {client.AddMembersToAccount(null,null);}catch(Exception e){}
        //try {client.GetMemberSettings(null,null);}catch(Exception e){}
		try {client.GetMembershipSummary(null);}catch(Exception e){}
        //try {client.GetConnectCredentials(null);}catch(Exception e){}
        //try {client.GetPlanPricingInformation(null,null,null);}catch(Exception e){}
        //try {client.NewAccount(null,null,null,null,null,null,null,null,null);}catch(Exception e){}
        //try {client.AuthenticateMember(null);}catch(Exception e){}
        //try {client.GetAccountDistributorCode(null);}catch(Exception e){}
		//try {client.ChangeAccountPricePlan(null,null,null,null,null,null,null,null);}catch(Exception e){}
        //try {client.GetAccountInformation(null);}catch(Exception e){}
        //try {client.UpdateMemberSettings(null,null,null);}catch(Exception e){}
        //try {client.Ping();}catch(Exception e){}
        //try {client.GetSuccessorPlanInformation(null,null,null);}catch(Exception e){}
        //try {client.GetPlanType(null);}catch(Exception e){}
        //try {client.AuthenticateMemberEx(null);}catch(Exception e){}
        //try {client.GetEncryptedPassword();}catch(Exception e){}
    }
}